### ISSUE TITLE
显示获取众筹失败

### ISSUE THREAD

**Issue by LUORANCHENG** [konicyQWQ/crowdfunding-dapp#2]
![图片](https://github.com/user-attachments/assets/3660655c-99be-4ada-9655-35e0b58f851a)

**Comment by LUORANCHENG** [comment]
系统：ubuntu22.04
node版本：v16.20.2
npm版本：8.19.4
yarn版本：1.22.22
ganache版本：v7.9.1
truffle版本：v5.11.5 (core: 5.11.5)
Solidity版本：v0.5.16 (solc-js)
Web3.js版本：v1.10.0

**Comment by QI7-T** [comment]
打开ganache
